(()=>{
const P={me:null,devices:[],active:null,page:'home',dash:null,items:[],today:null,health:[],watch:null};
const q=id=>document.getElementById(id),safe=s=>esc(s),fa=n=>Number(n||0).toLocaleString('fa-IR');
const icons={vaccination:'💉',medication:'💊',appointment:'🩺',grooming:'✂️',nutrition:'🥣',document:'📄',reminder:'🔔'};
const labels={vaccination:'واکسن',medication:'دارو',appointment:'دامپزشک',grooming:'نظافت',nutrition:'تغذیه',document:'مدارک',reminder:'یادآور'};
function redesignLanding(){const hero=document.querySelector('#landing .hero');if(!hero)return;hero.firstElementChild.innerHTML='<small style="color:#176e60;font-weight:900">همه زندگی پت، یک‌جا</small><h1>فقط نگاهش نکن؛<br><em>واقعاً مراقبش باش.</em></h1><p>برنامه غذا و دارو، واکسن و دامپزشک، پرونده سلامت، اعضای خانواده، دستیار هوشمند و دوربین زنده در یک اپ کامل.</p><div class="pc-trust"><span>۷ روز رایگان</span><span>پرونده جدا برای هر پت</span><span>یادآورهای قابل پیگیری</span></div><button class="btn primary" onclick="openAuth(\'register\')">ساخت پرونده رایگان</button> <button class="btn" onclick="openAuth(\'login\')">ورود</button>';hero.lastElementChild.innerHTML='<div class="pc-feature gold">♡<b>سلامت و رشد</b><span>وزن، علائم و سوابق</span></div><div class="pc-feature">💊<b>دارو و واکسن</b><span>برنامه و یادآور بعدی</span></div><div class="pc-feature">🥣<b>مراقبت روزانه</b><span>غذا، آب، بازی و نظافت</span></div><div class="pc-feature">✦<b>دستیار هوشمند</b><span>پاسخ بر اساس پرونده پت</span></div>'}
function date(v){if(!v)return'بدون زمان';return new Date(v).toLocaleString('fa-IR',{dateStyle:'medium',timeStyle:'short'})}
function active(){return P.devices.find(x=>x.id===P.active)}
function nav(){return [['home','⌂','امروز'],['care','✓','مراقبت'],['health','♡','سلامت'],['medical','✚','پرونده پزشکی'],['camera','◉','دوربین'],['ai','✦','دستیار هوشمند'],['family','♧','خانواده'],['profile','⚙','پروفایل']]}
function frame(){const pet=active();q('app').classList.remove('hidden');q('app').innerHTML=`<div class="pc-app"><div class="pc-shell"><header class="pc-top"><div class="pc-brand"><i>🐾</i><span>CamCam Care<small class="pc-muted" style="display:block">همراه زندگی پت</small></span></div><div><button class="pc-btn" onclick="ccPremium()">${P.me.entitlement?.plan==='premium'?'پریمیوم':'۷ روز رایگان'}</button> <button class="pc-btn danger" onclick="portalLogout()">خروج</button></div></header><div class="pc-layout"><aside class="pc-side"><div class="pc-pets">${P.devices.map(d=>`<button class="pc-pet ${d.id===P.active?'active':''}" onclick="portalPet('${d.id}')">${safe(d.pet?.pet_name||d.name)}</button>`).join('')}</div><nav class="pc-nav">${nav().map(x=>`<button class="${P.page===x[0]?'active':''}" onclick="portalPage('${x[0]}')">${x[1]} &nbsp; ${x[2]}</button>`).join('')}</nav><div class="pc-side-foot">${safe(P.me.email)}<br>اطلاعات هر پت جدا و امن نگهداری می‌شود.</div></aside><main class="pc-main"><div id="pcView"></div></main></div></div><nav class="pc-mobile-nav">${nav().slice(0,5).map(x=>`<button onclick="portalPage('${x[0]}')"><b>${x[1]}</b>${x[2]}</button>`).join('')}</nav></div>`;render()}
async function load(){if(!P.active)return;const id=P.active;activeId=id;activeDevice=P.devices.find(x=>x.id===id);const [dash,items,today,health]=await Promise.all([api(`/api/pet/devices/${id}/management/dashboard`),api(`/api/pet/devices/${id}/management/items`),api(`/api/pet/devices/${id}/care/today?local_date=${new Date().toISOString().slice(0,10)}`),api(`/api/pet/devices/${id}/health-logs`)]);P.dash=dash;P.items=items;P.today=today;P.health=health}
window.portalBoot=async()=>{try{P.me=await api('/api/me');P.devices=await api('/api/pet/devices');P.active=P.active&&P.devices.some(x=>x.id===P.active)?P.active:P.devices[0]?.id||null;await load();q('landing').classList.add('hidden');frame()}catch(e){if(e.status===401){q('landing').classList.remove('hidden');q('app').classList.add('hidden')}else toast(e.message)}};
window.boot=window.portalBoot;
window.portalLogout=async()=>{try{await api('/api/auth/logout',{method:'POST'})}catch{}location.reload()};
window.portalPet=async id=>{P.active=id;await load();frame()};window.portalPage=p=>{P.page=p;frame()};
function head(title,sub,action=''){return`<div class="pc-head"><div><h1>${title}</h1><div class="pc-muted">${sub}</div></div>${action}</div>`}
function itemRow(x){const overdue=x.due_at&&!x.completed_at&&new Date(x.due_at)<new Date();return`<div class="pc-item ${overdue?'overdue':''}"><div class="pc-icon">${icons[x.category]||'•'}</div><div class="pc-grow"><b>${safe(x.title)}</b><small>${labels[x.category]||x.category} · ${date(x.due_at)}${x.dosage?' · '+safe(x.dosage):''}</small></div><div class="pc-actions">${!x.completed_at?`<button class="pc-btn primary" onclick="portalComplete('${x.id}')">انجام شد</button>`:'✓'}<button class="pc-btn danger" onclick="portalDelete('${x.id}')">×</button></div></div>`}
function home(){const d=P.dash||{},t=P.today||{},pet=d.pet||{},total=+t.total||0,done=+t.completed||0,pct=total?Math.round(done*100/total):0;return head(`سلام، ${safe(pet.name||'دوست من')}!`,'خلاصه مراقبت امروز و وضعیت پت',`<button class="pc-btn gold" onclick="portalAddItem()">＋ یادآور جدید</button>`)+`<div class="pc-grid"><section class="pc-card pc-hero"><div class="pc-muted" style="color:#cde0da">امروز کنار هم مراقبت می‌کنیم</div><h2>${safe(pet.name||'پت')}</h2><p>${d.online?'دوربین آنلاین است':'دوربین آفلاین است'} · ${fa(d.counts?.pending)} برنامه باز</p><button class="pc-btn gold" onclick="portalPage('care')">مشاهده برنامه امروز</button></section><section class="pc-card pc-score"><div><div class="pc-ring" style="--p:${pct}%"><b>${fa(pct)}٪</b></div><div class="pc-muted" style="margin-top:10px">مراقبت انجام‌شده امروز</div></div></section><div class="pc-card pc-stat"><span class="pc-muted">کارهای عقب‌افتاده</span><b>${fa(d.counts?.overdue)}</b></div><div class="pc-card pc-stat"><span class="pc-muted">داروهای فعال</span><b>${fa(d.counts?.medications)}</b></div><div class="pc-card pc-stat"><span class="pc-muted">واکسن‌های پیش‌رو</span><b>${fa(d.counts?.vaccinations)}</b></div><div class="pc-card pc-stat"><span class="pc-muted">ثبت سلامت</span><b>${fa((d.recent_health||[]).length)}</b></div><section class="pc-card pc-wide"><div class="pc-section-title"><h3>نزدیک‌ترین برنامه‌ها</h3><button class="pc-btn" onclick="portalPage('medical')">همه</button></div><div class="pc-list">${[...(d.overdue||[]),...(d.upcoming||[])].slice(0,5).map(itemRow).join('')||'<div class="pc-empty">برنامه‌ای ثبت نشده؛ اولین یادآور را بساز.</div>'}</div></section><section class="pc-card pc-narrow"><div class="pc-section-title"><h3>ثبت سریع</h3></div><div class="pc-quick"><button onclick="portalQuick('feed','غذا')"><b>🥣</b>غذا</button><button onclick="portalQuick('water','آب')"><b>💧</b>آب</button><button onclick="portalQuick('walk','پیاده‌روی')"><b>🦮</b>قدم‌زدن</button><button onclick="portalHealth()"><b>♡</b>سلامت</button></div></section></div>`}
function care(){const t=P.today||{},tasks=t.tasks||[],done=new Set(t.done_task_ids||[]);return head('مراقبت روزانه','روتین‌های غذا، آب، بازی، نظافت و فعالیت',`<button class="pc-btn primary" onclick="ccAdd()">＋ برنامه روزانه</button>`)+`<div class="pc-grid"><section class="pc-card pc-wide"><div class="pc-section-title"><h3>برنامه امروز</h3><span>${fa(t.completed)}/${fa(t.total)}</span></div><div class="pc-list">${tasks.map(x=>`<div class="pc-item"><div class="pc-icon">${icons[x.kind]||'✓'}</div><div class="pc-grow"><b>${safe(x.title)}</b><small>${x.time_of_day||'تمام روز'}</small></div>${done.has(x.id)?'✓ انجام شد':`<button class="pc-btn primary" onclick="portalDone('${x.id}')">انجام شد</button>`}</div>`).join('')||'<div class="pc-empty">هنوز برنامه روزانه‌ای نداری.</div>'}</div></section><section class="pc-card pc-narrow"><h3>ثبت سریع</h3><div class="pc-quick"><button onclick="portalQuick('feed','وعده غذایی')"><b>🥣</b>غذا</button><button onclick="portalQuick('water','آب تازه')"><b>💧</b>آب</button><button onclick="portalQuick('toilet','دستشویی')"><b>🐾</b>دستشویی</button><button onclick="portalQuick('play','بازی')"><b>🎾</b>بازی</button></div></section></div>`}
function health(){return head('سلامت و رشد','وزن، علائم، اشتها، آب و سابقه پزشکی',`<button class="pc-btn primary" onclick="portalHealth()">＋ ثبت سلامت</button>`)+`<div class="pc-grid"><section class="pc-card pc-full"><div class="pc-list">${P.health.map(x=>`<div class="pc-item"><div class="pc-icon">♡</div><div class="pc-grow"><b>${safe(x.value||labels[x.kind]||x.kind)}</b><small>${safe(x.note||'بدون یادداشت')} · ${date(x.happened_at)}</small></div></div>`).join('')||'<div class="pc-empty">هنوز سابقه سلامتی ثبت نشده.</div>'}</div></section></div>`}
function medical(){const categories=['vaccination','medication','appointment','document','grooming','nutrition','reminder'];return head('پرونده و یادآورها','واکسن، دارو، نوبت، مدارک، تغذیه و نظافت',`<button class="pc-btn primary" onclick="portalAddItem()">＋ مورد جدید</button>`)+`<div class="pc-tabs">${categories.map(c=>`<button class="pc-btn" onclick="portalFilter('${c}')">${icons[c]} ${labels[c]}</button>`).join('')}</div><div class="pc-card"><div id="pcItems" class="pc-list">${P.items.filter(x=>!x.completed_at).map(itemRow).join('')||'<div class="pc-empty">موردی ثبت نشده.</div>'}</div></div>`}
function camera(){const d=active();return head('دوربین و ارتباط','مشاهده زنده فقط یکی از ابزارهای مراقبت است')+`<div class="pc-grid"><section class="pc-card pc-wide"><video id="liveVideo" class="pc-video" autoplay playsinline controls></video><div id="pcCamState" class="pc-muted" style="margin-top:8px">${d.online?'آماده اتصال':'دوربین آفلاین است'}</div></section><section class="pc-card pc-narrow"><h3>${safe(d.pet?.pet_name||d.name)}</h3><p class="pc-muted">${d.online?'آنلاین':'آفلاین'}</p><div class="pc-list"><button class="pc-btn primary" onclick="portalWatch()">شروع پخش زنده</button><button class="pc-btn" onclick="portalCommand('say','بیا پیشم')">🔊 بیا پیشم</button><button class="pc-btn" onclick="portalCommand('torch',true)">🔦 روشن‌کردن چراغ</button></div></section></div>`}
function ai(){return head('دستیار هوشمند پت','پاسخ شخصی‌سازی‌شده با توجه به پروفایل و سوابق پت')+`<div class="pc-card"><div id="pcQuota" class="pc-muted">در حال دریافت سهمیه…</div><div id="pcChat" class="pc-chat"><div class="pc-msg bot">هر سؤالی درباره مراقبت، برنامه یا سوابق ${safe(active()?.pet?.pet_name||'پت')} داری بپرس.</div></div><form class="pc-form-grid" onsubmit="portalAsk(event)"><div class="pc-field"><textarea id="pcQuestion" required maxlength="1200" placeholder="مثلاً واکسن بعدی چه زمانی است؟"></textarea></div><button class="pc-btn primary">ارسال</button></form></div>`}
function family(){return head('خانواده و مراقبان','دسترسی اعضای خانواده را مدیریت کن',`<button class="pc-btn primary" onclick="portalShare()">＋ افزودن مراقب</button>`)+`<div class="pc-card"><div id="pcShares" class="pc-list">در حال بارگذاری…</div></div>`}
function profile(){const d=P.dash||{},p=d.pet?.profile||{};return head('پروفایل پت','هویت، ویژگی‌ها و اطلاعات تماس دامپزشک',`<button class="pc-btn primary" onclick="ccProfile()">ویرایش پروفایل</button>`)+`<div class="pc-grid"><section class="pc-card pc-narrow"><div class="pc-icon" style="width:72px;height:72px;font-size:34px">${active()?.pet?.pet_type==='cat'?'🐈':'🐕'}</div><h2>${safe(d.pet?.name||'پت')}</h2><p class="pc-muted">${safe(p.breed||'نژاد ثبت نشده')}</p></section><section class="pc-card pc-wide"><div class="pc-form-grid"><div><span class="pc-muted">وزن</span><b style="display:block">${p.weight_kg||'—'} کیلو</b></div><div><span class="pc-muted">تولد</span><b style="display:block">${safe(p.birth_date||'—')}</b></div><div><span class="pc-muted">دامپزشک</span><b style="display:block">${safe(p.vet_name||'—')}</b></div><div><span class="pc-muted">میکروچیپ</span><b style="display:block">${safe(p.microchip||'—')}</b></div><div><span class="pc-muted">حساسیت</span><b style="display:block">${safe(p.allergies||'—')}</b></div><div><span class="pc-muted">یادداشت پزشکی</span><b style="display:block">${safe(p.medical_notes||'—')}</b></div></div></section></div>`}
function render(){if(!P.active){q('pcView').innerHTML=head('اولین پتت را اضافه کن','برای شروع یک دوربین/پت بساز',`<button class="pc-btn primary" onclick="addCamera()">＋ افزودن پت</button>`);return}const f={home,care,health,medical,camera,ai,family,profile}[P.page]||home;q('pcView').innerHTML=f();if(P.page==='ai')portalAIStatus();if(P.page==='family')portalShares()}
window.portalAddItem=()=>openModal(`<button class="close" onclick="closeModal()">×</button><h3>مورد مراقبتی جدید</h3><form onsubmit="portalSaveItem(event)"><div class="pc-form-grid"><div class="pc-field"><label>نوع</label><select id="piCategory">${Object.keys(labels).map(x=>`<option value="${x}">${labels[x]}</option>`).join('')}</select></div><div class="pc-field"><label>عنوان</label><input id="piTitle" required maxlength="140"></div><div class="pc-field"><label>زمان</label><input id="piDue" type="datetime-local"></div><div class="pc-field"><label>تکرار هر چند روز</label><input id="piRepeat" type="number" min="1"></div><div class="pc-field"><label>دامپزشک / ارائه‌دهنده</label><input id="piProvider"></div><div class="pc-field"><label>دوز دارو</label><input id="piDosage"></div></div><div class="pc-field"><label>یادداشت</label><textarea id="piNotes"></textarea></div><button class="pc-btn primary" style="width:100%">ذخیره</button></form>`);
window.portalSaveItem=async e=>{e.preventDefault();await api(`/api/pet/devices/${P.active}/management/items`,{method:'POST',body:JSON.stringify({category:q('piCategory').value,title:q('piTitle').value,due_at:q('piDue').value?new Date(q('piDue').value).toISOString():null,repeat_days:q('piRepeat').value?+q('piRepeat').value:null,provider:q('piProvider').value,dosage:q('piDosage').value,notes:q('piNotes').value,metadata:{}})});closeModal();await load();render();toast('ذخیره شد')};
window.portalComplete=async id=>{await api(`/api/pet/devices/${P.active}/management/items/${id}/complete`,{method:'POST'});await load();render();toast('انجام شد')};window.portalDelete=async id=>{if(!confirm('حذف شود؟'))return;await api(`/api/pet/devices/${P.active}/management/items/${id}`,{method:'DELETE'});await load();render()};
window.portalFilter=c=>{q('pcItems').innerHTML=P.items.filter(x=>x.category===c&&!x.completed_at).map(itemRow).join('')||'<div class="pc-empty">موردی در این بخش نیست.</div>'};
window.portalQuick=async(kind,title)=>{await api(`/api/pet/devices/${P.active}/care/logs`,{method:'POST',body:JSON.stringify({local_date:new Date().toISOString().slice(0,10),kind,title,note:''})});await load();render();toast('ثبت شد')};window.portalDone=async id=>{await api(`/api/pet/devices/${P.active}/care/tasks/${id}/done`,{method:'POST',body:JSON.stringify({local_date:new Date().toISOString().slice(0,10),note:''})});await load();render()};
window.portalHealth=()=>ccHealth();window.portalWatch=async()=>{try{q('pcCamState').textContent='در حال اتصال…';const auth=await api(`/api/pet/devices/${P.active}/watch-token`,{method:'POST'});if(P.watch)P.watch.close();P.watch=await connectWatch(auth);q('pcCamState').textContent='● زنده'}catch(e){q('pcCamState').textContent=e.message}};window.portalCommand=async(type,value)=>{try{await api(`/api/pet/devices/${P.active}/command`,{method:'POST',body:JSON.stringify({type,value})});toast('دستور ارسال شد')}catch(e){toast(e.message)}};
window.portalAIStatus=async()=>{try{const x=await api(`/api/pet/devices/${P.active}/ai/status`);q('pcQuota').textContent=`${fa(x.remaining)} از ${fa(x.daily_limit)} پرسش امروز باقی مانده`}catch(e){q('pcQuota').textContent=e.message}};window.portalAsk=async e=>{e.preventDefault();const v=q('pcQuestion').value.trim(),chat=q('pcChat');chat.insertAdjacentHTML('beforeend',`<div class="pc-msg user">${safe(v)}</div>`);q('pcQuestion').value='';try{const x=await api(`/api/pet/devices/${P.active}/ai/ask`,{method:'POST',body:JSON.stringify({question:v})});chat.insertAdjacentHTML('beforeend',`<div class="pc-msg bot">${safe(x.answer)}</div>`);q('pcQuota').textContent=`${fa(x.remaining)} پرسش باقی مانده`}catch(e){chat.insertAdjacentHTML('beforeend',`<div class="pc-msg bot">${safe(e.message)}</div>`)}chat.scrollTop=chat.scrollHeight};
window.portalShares=async()=>{try{const x=await api(`/api/pet/devices/${P.active}/shares`);q('pcShares').innerHTML=x.map(s=>`<div class="pc-item"><div class="pc-icon">👤</div><div class="pc-grow"><b>${safe(s.email)}</b><small>${s.role==='caregiver'?'مراقب کامل':'فقط مشاهده'}</small></div><button class="pc-btn danger" onclick="portalRemoveShare('${s.id}')">حذف</button></div>`).join('')||'<div class="pc-empty">هنوز مراقبی اضافه نشده.</div>'}catch(e){q('pcShares').textContent=e.message}};window.portalShare=()=>openModal(`<button class="close" onclick="closeModal()">×</button><h3>افزودن مراقب</h3><form onsubmit="portalSaveShare(event)"><div class="pc-field"><label>ایمیل</label><input id="psEmail" type="email" required></div><div class="pc-field"><label>دسترسی</label><select id="psRole"><option value="caregiver">مراقب کامل</option><option value="viewer">فقط مشاهده</option></select></div><button class="pc-btn primary" style="width:100%">افزودن</button></form>`);window.portalSaveShare=async e=>{e.preventDefault();await api(`/api/pet/devices/${P.active}/shares`,{method:'POST',body:JSON.stringify({email:q('psEmail').value,role:q('psRole').value})});closeModal();portalShares()};window.portalRemoveShare=async id=>{await api(`/api/pet/devices/${P.active}/shares/${id}`,{method:'DELETE'});portalShares()};
redesignLanding();setTimeout(portalBoot,0);
})();
