(function(){
'use strict';
const sleep2=ms=>new Promise(r=>setTimeout(r,ms));
function style(){
  if(document.getElementById('camcam-controls-hotfix-style')) return;
  const s=document.createElement('style');s.id='camcam-controls-hotfix-style';s.textContent=`
  :root{--coral:#ef765d;--coral-soft:#fff0ea;--glass:rgba(255,253,249,.76);--glass-line:rgba(216,202,184,.76);--elev:0 20px 55px rgba(37,67,62,.10);--elev2:0 10px 28px rgba(37,67,62,.07)}
  body{background:radial-gradient(circle at 92% 0,rgba(21,145,137,.13),transparent 27%),radial-gradient(circle at 4% 32%,rgba(239,118,93,.09),transparent 22%),linear-gradient(180deg,#faf6ef,#f5eee4 60%,#faf7f1)!important;background-attachment:fixed!important}
  body:before{content:'';position:fixed;inset:0;z-index:-1;pointer-events:none;opacity:.18;background-image:linear-gradient(rgba(13,107,102,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(13,107,102,.08) 1px,transparent 1px);background-size:42px 42px;mask-image:linear-gradient(#000,transparent 82%)}
  .shell{width:min(1180px,100%)!important;padding:0 18px!important}.app{padding-bottom:110px!important}.top{height:84px!important;position:sticky;top:0;z-index:55;background:rgba(250,246,239,.82);backdrop-filter:blur(20px);border-bottom:1px solid rgba(222,212,197,.72);margin:0 -18px 20px;padding:0 18px!important}.logo{font-size:21px!important;letter-spacing:-.4px}.logo small{font-size:9px!important}.account{padding:8px 12px;border:1px solid var(--line);border-radius:14px;background:rgba(255,255,255,.58);backdrop-filter:blur(10px)}
  .layout{grid-template-columns:210px 1fr!important;gap:18px!important}.sidebar{padding:10px!important;border-radius:25px!important;background:var(--glass)!important;backdrop-filter:blur(18px);border:1px solid var(--glass-line)!important;box-shadow:var(--elev2)!important;top:102px!important}.side{padding:13px!important;border-radius:14px!important;font-size:11px;transition:.2s}.side:hover{background:#f4f0e8;color:var(--brand)}.side.active{background:linear-gradient(135deg,#dff0ec,#edf7f3)!important;color:var(--brand)!important}
  .head{margin:4px 0 18px!important}.head h1{font-size:30px!important;letter-spacing:-1px}.head .muted{font-size:10px}.head .btn.primary{border-radius:15px!important;padding:12px 17px!important;box-shadow:0 10px 26px rgba(13,107,102,.17)}
  .summary{gap:11px!important;margin-bottom:14px!important}.sum{position:relative;overflow:hidden;background:var(--glass)!important;backdrop-filter:blur(12px);border:1px solid var(--glass-line)!important;border-radius:21px!important;padding:16px!important;box-shadow:var(--elev2)!important;min-height:94px}.sum:after{content:'';position:absolute;width:52px;height:52px;border-radius:50%;left:-17px;bottom:-20px;background:rgba(21,145,137,.08)}.sum small{font-size:9px!important}.sum b{font-size:25px!important;margin-top:7px!important}.sum:nth-child(2) b{color:#2f8158}.sum:nth-child(3) b{color:var(--coral)}
  .cams{gap:13px!important}.card{border-radius:25px!important;border:1px solid var(--glass-line)!important;background:var(--glass)!important;backdrop-filter:blur(13px);box-shadow:var(--elev2)!important;transition:.25s}.card:hover{transform:translateY(-3px);box-shadow:var(--elev)!important}.cover{height:190px!important;border-radius:24px 24px 0 0;background:linear-gradient(145deg,#a8c8c1,#5e958b 56%,#225d56)!important}.cover:before{content:'';position:absolute;inset:0;background-image:linear-gradient(rgba(255,255,255,.13) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.13) 1px,transparent 1px);background-size:33.33% 33.33%;opacity:.5}.cover:after{font-size:86px!important;opacity:.13!important}.pill{padding:6px 9px!important;box-shadow:0 5px 18px rgba(0,0,0,.07)}.body{padding:14px!important}.chip{border-radius:999px!important;padding:5px 8px!important;background:#edf5f2!important}.actions{gap:7px!important}.actions .btn{border-radius:12px!important;min-height:39px}
  .detail{padding:18px!important;margin-top:16px!important;border-radius:30px!important;background:rgba(255,253,249,.90)!important;backdrop-filter:blur(20px);border:1px solid var(--glass-line)!important;box-shadow:var(--elev)!important}.detail-head{padding:3px 3px 4px}.detail-head b{font-size:22px}.detail-head small{font-size:9px}.tabs{gap:7px!important;margin:14px 0!important;padding-bottom:2px}.tab{border-radius:999px!important;padding:9px 13px!important;background:#fffdf9!important;transition:.2s}.tab.active{background:var(--dark)!important;color:#fff!important;box-shadow:0 8px 20px rgba(16,43,42,.16)}
  .video-grid{grid-template-columns:1fr!important;gap:0!important;position:relative}.video{aspect-ratio:16/9!important;min-height:330px;border-radius:25px!important;box-shadow:0 20px 48px rgba(8,27,25,.18);border:1px solid #203b38}.video:after{content:'';position:absolute;inset:0;pointer-events:none;background:linear-gradient(180deg,transparent 67%,rgba(0,0,0,.18));z-index:1}.video video{position:relative;z-index:0}.state{z-index:4!important;right:13px!important;top:13px!important;padding:7px 11px!important;border-radius:999px!important;background:rgba(255,247,239,.94)!important;color:#a64e45;box-shadow:0 7px 20px rgba(0,0,0,.08)}
  .care{position:relative;z-index:5;margin:-30px 20px 0;padding:13px;border-radius:23px;background:rgba(255,253,249,.82);backdrop-filter:blur(18px);border:1px solid rgba(255,255,255,.75);box-shadow:0 18px 42px rgba(31,60,55,.13);grid-template-columns:1.1fr 1fr;gap:10px!important}.talk{grid-column:1/-1;min-height:76px!important;border-radius:20px!important;background:linear-gradient(135deg,var(--brand),var(--brand2))!important;box-shadow:0 14px 30px rgba(13,107,102,.23);font-size:14px!important;position:relative;overflow:hidden}.talk:before,.talk:after{content:'';position:absolute;left:18%;top:50%;width:36px;height:36px;border:1px solid rgba(255,255,255,.3);border-radius:50%;transform:translate(-50%,-50%);animation:ccRipple 2.1s infinite}.talk:after{animation-delay:1.05s}@keyframes ccRipple{to{width:105px;height:105px;opacity:0}}.talk.active{background:linear-gradient(135deg,#a43f50,#d56872)!important}.talk.active:before,.talk.active:after{animation-duration:.9s}
  .controls{grid-column:1/-1;display:grid!important;grid-template-columns:repeat(4,1fr)!important;gap:8px!important}.toggle,.action{min-height:68px!important;border-radius:17px!important;padding:10px 12px!important;box-shadow:0 5px 16px rgba(37,67,62,.035);transition:.2s!important}.toggle,.action{background:rgba(255,255,255,.82)!important;border:1px solid var(--line)!important}.toggle:hover,.action:hover{transform:translateY(-1px);border-color:#a8c9c2!important}.toggle{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:10px!important;text-align:right!important;color:var(--ink)!important}.toggle .cc-copy{display:grid;gap:3px}.toggle .cc-copy strong{font-size:11px}.toggle .cc-copy small{font-size:8px;color:var(--muted);font-weight:500}.toggle .cc-switch{width:46px;height:27px;border-radius:99px;background:#ddd5c9;position:relative;flex:0 0 auto;transition:.2s}.toggle .cc-switch:after{content:'';position:absolute;top:3px;right:3px;width:21px;height:21px;border-radius:50%;background:#fff;box-shadow:0 2px 7px rgba(0,0,0,.18);transition:.2s}.toggle.on{background:#edf8f4!important;border-color:#8ab8af!important;color:var(--brand)!important}.toggle.on .cc-switch{background:var(--brand2)}.toggle.on .cc-switch:after{right:22px}.action{display:grid!important;align-content:center!important;text-align:right!important}.action strong{font-size:11px}.action small{font-size:8px;color:var(--muted);font-weight:500;margin-top:3px}.manual.recording{background:#fff0f2!important;color:#9d3948!important;border-color:#e6aab4!important}
  #controlNote{grid-column:1/-1;border-radius:13px;padding:9px 11px;background:#f7f4ee;border:1px solid #eee5d8;min-height:34px!important;display:flex;align-items:center}#controlNote.cc-ok{background:#edf7f3;color:#2f8158;border-color:#cde8dd}#controlNote.cc-bad{background:#fff1f2;color:#a64050;border-color:#f0c8ce}
  .zoomq{grid-column:1/-1;grid-template-columns:1fr 170px!important;gap:9px!important}.zoom,.quality{border-radius:16px!important;background:#fff!important;border:1px solid var(--line)!important}.zoom{padding:11px!important}.zoom div{font-size:10px!important}.zoom input{accent-color:var(--brand2);height:22px}.quality{padding:12px!important}.phrases{grid-column:1/-1;gap:7px!important}.phrases .btn{border-radius:999px!important;padding:9px 13px!important;background:#fff!important}.health{grid-column:1/-1;background:#eef7f4!important;border:1px solid #d8ebe5;border-radius:14px!important;padding:11px!important}
  .pane{border-radius:21px!important;padding:15px!important;background:rgba(255,250,243,.72)!important;backdrop-filter:blur(12px);border:1px solid var(--glass-line)!important}.timeline{display:flex!important;gap:10px!important;overflow-x:auto!important;padding:3px 2px 10px;scroll-snap-type:x proximity}.event,.record,.share{min-width:250px;max-width:340px;flex:0 0 auto;align-items:stretch!important;flex-direction:column;border-radius:17px!important;padding:10px!important;background:#fff!important;box-shadow:0 6px 18px rgba(40,69,64,.04);scroll-snap-align:start}.event img{width:100%!important;height:130px!important;border-radius:13px!important;object-fit:cover!important}.event .info{width:100%;padding:2px}.event .btn,.record .btn{width:100%;margin-top:auto}.record{min-height:112px;justify-content:space-between!important}.share{min-width:100%;flex-direction:row!important;align-items:center!important}.empty{min-width:100%;border-radius:17px!important;background:rgba(255,255,255,.5)}
  .settings{gap:10px!important}.switchrow{border-radius:15px!important;padding:12px!important}.field input,.field select{border-radius:13px!important;padding:11px!important}.modalback{backdrop-filter:blur(8px)}.modal{border-radius:27px!important;padding:20px!important;box-shadow:0 30px 90px rgba(0,0,0,.25)}.modal video{border-radius:18px!important}.toast{left:18px!important;bottom:22px!important;border-radius:16px!important;padding:12px 14px!important;box-shadow:0 16px 40px rgba(0,0,0,.2)}
  .bottom{backdrop-filter:blur(18px);background:rgba(255,253,249,.86)!important;box-shadow:0 13px 45px rgba(32,61,56,.13);border-radius:22px!important}.bottom button{border-radius:15px!important;transition:.2s}.bottom button:active{background:#e7f2ef!important;color:var(--brand)!important}
  @media(max-width:850px){.layout{grid-template-columns:1fr!important}.top{margin:0 -10px 14px;padding:0 12px!important}.detail{padding:12px!important;border-radius:25px!important}.care{margin:-20px 8px 0!important;grid-template-columns:1fr!important}.controls{grid-template-columns:1fr 1fr!important}.video{min-height:0!important}.summary{gap:8px!important}.sum{min-height:84px!important;padding:13px!important}.head h1{font-size:25px!important}.timeline{margin-left:-3px;margin-right:-3px}.event,.record{min-width:78vw}.bottom{right:12px!important;left:12px!important;bottom:max(10px,env(safe-area-inset-bottom))!important;padding:6px!important}}
  @media(max-width:520px){.shell{padding:0 10px!important}.top{height:78px!important}.account{display:none}.summary{grid-template-columns:1fr 1fr!important}.sum b{font-size:21px!important}.controls{grid-template-columns:1fr 1fr!important}.toggle,.action{min-height:64px!important}.zoomq{grid-template-columns:1fr!important}.phrases{display:grid!important;grid-template-columns:repeat(3,1fr)!important}.phrases .btn{padding:8px 4px!important;font-size:8px!important}.care{padding:10px!important}.video{border-radius:22px!important}.detail-head b{font-size:19px}.top .btn.danger{display:inline-flex!important}.logo{font-size:18px!important}.event,.record{min-width:84vw}}
  `;document.head.appendChild(s);
}
function enhanceControls(){
  const torch=document.getElementById('torch'), low=document.getElementById('lowPower'), manual=document.getElementById('manual');
  if(torch&&!torch.querySelector('.cc-switch')) torch.innerHTML='<span class="cc-copy"><strong>🔦 چراغ</strong><small id="ccTorchState">خاموش</small></span><span class="cc-switch" aria-hidden="true"></span>';
  if(low&&!low.querySelector('.cc-switch')) low.innerHTML='<span class="cc-copy"><strong>🌙 حالت کم‌مصرف</strong><small id="ccLowState">خاموش</small></span><span class="cc-switch" aria-hidden="true"></span>';
  const rotate=[...document.querySelectorAll('.action')].find(x=>(x.getAttribute('onclick')||'').includes('rotateCamera'));
  if(rotate&&!rotate.querySelector('strong')) rotate.innerHTML='<strong>🔄 چرخش دوربین</strong><small>جابجایی بین دوربین جلو و پشت</small>';
  if(manual&&!manual.querySelector('strong')) manual.innerHTML='<strong id="ccManualTitle">⏺ ضبط دستی</strong><small id="ccManualState">برای شروع لمس کن</small>';
}
function setNote2(msg,ok){const n=document.getElementById('controlNote');if(!n)return;n.textContent=msg||'';n.classList.remove('cc-ok','cc-bad');if(ok===true)n.classList.add('cc-ok');if(ok===false)n.classList.add('cc-bad');}
style();enhanceControls();

try{
  renderControl=function(){
    enhanceControls();
    const torch=document.getElementById('torch'),low=document.getElementById('lowPower');
    if(torch){torch.classList.toggle('on',!!control.torch);const s=document.getElementById('ccTorchState');if(s)s.textContent=control.torch?'روشن':'خاموش';}
    if(low){low.classList.toggle('on',!!control.low);const s=document.getElementById('ccLowState');if(s)s.textContent=control.low?'روشن':'خاموش';}
    const zr=document.getElementById('zoomRange'),zv=document.getElementById('zoomVal');if(zr)zr.value=control.zoom;if(zv)zv.textContent=Number(control.zoom).toFixed(1)+'×';
  };
  renderManual=function(){
    enhanceControls();const b=document.getElementById('manual');if(!b)return;const title=document.getElementById('ccManualTitle'),state=document.getElementById('ccManualState');
    if(manualActive){const n=Math.max(0,Math.floor((Date.now()-new Date(manualActive.started_at))/1000));b.classList.add('recording');if(title)title.textContent='⏹ پایان ضبط';if(state)state.textContent=n+' ثانیه در حال ضبط';}
    else{b.classList.remove('recording');if(title)title.textContent='⏺ ضبط دستی';if(state)state.textContent='برای شروع لمس کن';}
  };
  const oldCmd=cmd;
  cmd=async function(type,value,quiet=false){setNote2('در حال اعمال روی دوربین…');const a=await oldCmd(type,value,true);if(a){setNote2(a.message||'دستور اجرا شد.',a.ok!==false);}else setNote2('پاسخ دوربین دریافت نشد.',false);if(!quiet)toast(a?.message||'پاسخ دوربین دریافت نشد');return a;};
  syncControl=function(){const t=activeDevice?.telemetry||{},p=activeDevice?.pet||{};if(t.torch!=null)control.torch=!!t.torch;control.low=!!t.low_power;control.quality=t.quality||p.quality||'720p';if(t.zoom!=null)control.zoom=Number(t.zoom)||1;const q=document.getElementById('quality');if(q)q.value=control.quality;renderControl();};
}catch(e){console.warn('CamCam controls override',e)}

let talkStarting2=false;
async function ensureMic2(){
  try{
    if(!window.CamCamNative?.hasMicrophonePermission) return true;
    if(window.CamCamNative.hasMicrophonePermission()) return true;
    return await new Promise(resolve=>{let settled=false;const done=e=>{if(settled)return;settled=true;resolve(!!e.detail?.granted)};window.addEventListener('camcam-native-mic',done,{once:true});window.CamCamNative.requestMicrophonePermission();setTimeout(()=>{if(!settled){settled=true;resolve(!!window.CamCamNative?.hasMicrophonePermission?.())}},7000)});
  }catch{return true}
}
async function getMic2(){let last=null;for(const cfg of [{audio:true,video:false},{audio:{echoCancellation:true,noiseSuppression:true,channelCount:1},video:false}]){try{return await navigator.mediaDevices.getUserMedia(cfg)}catch(e){last=e;await sleep2(250)}}throw last||new Error('میکروفن در دسترس نیست')}
async function startTalk2(e){
  if(!activeId||activeDevice?.access==='viewer'||talkPC||talkStarting2)return;e?.preventDefault();talkStarting2=true;const b=document.getElementById('talk');b?.classList.add('active');if(b)b.textContent='در حال آماده‌سازی میکروفن…';
  try{
    if(!await ensureMic2())throw new Error('اجازه میکروفن داده نشد');
    talkStream=await getMic2();
    await api(`/api/pet/devices/${activeId}/talk-wake`,{method:'POST'}).catch(()=>{});
    const auth=await api(`/api/pet/devices/${activeId}/talk-token`,{method:'POST'}),p=newPeer();talkPC=p;talkStream.getTracks().forEach(t=>p.addTrack(t,talkStream));const o=await p.createOffer();await p.setLocalDescription(o);await waitIce(p);const r=await fetch(auth.whip_url,{method:'POST',headers:{'Content-Type':'application/sdp','Authorization':'Bearer '+auth.token},body:p.localDescription.sdp});if(!r.ok)throw new Error('مسیر صحبت برقرار نشد ('+r.status+')');talkResource=r.headers.get('Location');await p.setRemoteDescription({type:'answer',sdp:await r.text()});if(b)b.textContent='🎙 در حال صحبت…';
  }catch(err){toast('میکروفن شروع نشد: '+(err?.message||'خطای نامشخص'));await stopTalk2();}finally{talkStarting2=false}
}
async function stopTalk2(){const b=document.getElementById('talk');if(b){b.classList.remove('active');b.textContent='🎙 نگه دار و صحبت کن'}if(talkStream)talkStream.getTracks().forEach(t=>t.stop());talkStream=null;if(talkPC)try{talkPC.close()}catch{}talkPC=null;if(talkResource){try{await fetch(talkResource,{method:'DELETE'})}catch{}talkResource=null}talkStarting2=false}
const oldTalk=document.getElementById('talk');if(oldTalk){const fresh=oldTalk.cloneNode(true);oldTalk.parentNode.replaceChild(fresh,oldTalk);fresh.addEventListener('pointerdown',startTalk2,{passive:false});['pointerup','pointercancel','pointerleave'].forEach(x=>fresh.addEventListener(x,stopTalk2,{passive:true}));}
try{startTalk=startTalk2;stopTalk=stopTalk2;}catch{}
try{renderControl();renderManual();}catch{}
})();
