(function(){
'use strict';
const E=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cache=new Map(), caps=new Map();
const dateKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const kind=k=>({feed:['🍽️','غذا'],water:['💧','آب'],walk:['🐾','پیاده‌روی'],medication:['💊','دارو'],grooming:['✦','نظافت'],play:['●','بازی'],custom:['✓','مراقبت']}[k]||['✓','مراقبت']);
function installStyle(){
 if(!document.getElementById('cc-estedad')){const l=document.createElement('link');l.id='cc-estedad';l.rel='stylesheet';l.href='https://fonts.googleapis.com/css2?family=Estedad:wght@400;500;600;700;800&display=swap';document.head.appendChild(l)}
 if(document.getElementById('cc-care-style'))return;const s=document.createElement('style');s.id='cc-care-style';s.textContent=`
 body,button,input,select,textarea{font-family:"Estedad",Tahoma,Arial,sans-serif!important}.btn.small,.tab,.chip,.pill{font-size:10.5px!important}.note,.health,.field label{font-size:9.5px!important}
 .cc-care{display:grid;gap:10px}.cc-box{background:#fff;border:1px solid var(--cc-line,#e1ddd5);border-radius:17px;padding:12px}.cc-head{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-bottom:9px}.cc-head b{font-size:12px}.cc-muted{font-size:9px;color:var(--cc-muted,#71807b)}
 .cc-profile{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center}.cc-profile h3{margin:0 0 4px;font-size:17px}.cc-score{min-width:72px;text-align:center;border-radius:14px;padding:9px;background:var(--cc-brand-soft,#e4f2ef)}.cc-score b{display:block;font-size:20px;color:var(--cc-brand,#0b6f69)}
 .cc-meta{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.cc-meta span{font-size:9px;background:#f5f4f0;border-radius:9px;padding:5px 7px}.cc-tasks{display:grid;gap:7px}.cc-task{display:grid;grid-template-columns:auto 1fr auto;gap:8px;align-items:center;border:1px solid #e7e3db;border-radius:12px;padding:8px;background:#fff}.cc-task.done{background:#eef7f3}.cc-check{width:32px;height:32px;border:1px solid #d5ddd9;border-radius:9px;background:#fff;color:#0b6f69;font-weight:800}.cc-task.done .cc-check{background:#0b6f69;color:#fff}.cc-task b{font-size:10.5px}.cc-task small{display:block;font-size:8.5px;color:#71807b;margin-top:2px}.cc-x{border:0;background:none;color:#9a5964;font-size:16px}
 .cc-quick{display:grid;grid-template-columns:repeat(5,1fr);gap:6px}.cc-quick button{min-height:55px;border:1px solid #e4e0d8;border-radius:11px;background:#fff;font-size:9px;font-weight:700;color:#24443f}.cc-quick button b{display:block;font-size:16px}.cc-log{display:flex;gap:8px;align-items:center;border-bottom:1px solid #ece8e1;padding:7px 1px}.cc-log:last-child{border-bottom:0}.cc-log b{font-size:15px}.cc-log strong{font-size:10px}.cc-log small{display:block;color:#71807b;font-size:8px}.cc-mini{display:flex;justify-content:space-between;margin:7px 0 9px;padding:7px 9px;border-radius:10px;background:#f3f6f3;font-size:9px;color:#536c67}.cc-mini b{color:#173c3a}
 .cc-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}textarea.cc-text{width:100%;min-height:72px;border:1px solid var(--cc-line,#e1ddd5);border-radius:10px;padding:9px;resize:vertical}.cc-empty{text-align:center;color:#71807b;padding:13px;font-size:10px}
 @media(max-width:620px){.cc-quick{grid-template-columns:repeat(3,1fr)}.cc-grid{grid-template-columns:1fr}.cc-profile{grid-template-columns:1fr auto}}
 `;document.head.appendChild(s)
}
async function today(id,force=false){const key=id+':'+dateKey();if(!force&&cache.has(key))return cache.get(key);const d=await api(`/api/pet/devices/${id}/care/today?local_date=${dateKey()}`);cache.set(key,d);return d}
async function capabilities(id,force=false){if(!force&&caps.has(id))return caps.get(id);try{const d=await api(`/api/pet/devices/${id}/capabilities`);caps.set(id,d||{});return d||{}}catch{return {}}}
function installTab(){const tabs=document.querySelector('#detail .tabs'),settings=tabs?.querySelector('[data-tab="settings"]');if(!tabs||!settings||tabs.querySelector('[data-tab="care"]'))return;const b=document.createElement('button');b.className='tab';b.dataset.tab='care';b.textContent='مراقبت';b.onclick=()=>showTab('care');tabs.insertBefore(b,settings);const p=document.createElement('div');p.id='careTab';p.className='hidden';p.innerHTML='<div id="ccCare" class="cc-care"><div class="cc-empty">در حال بارگذاری…</div></div>';document.getElementById('settingsTab')?.before(p)}
function render(d){const root=document.getElementById('ccCare');if(!root||!activeId)return;const pet=activeDevice?.pet||{},profile=d.profile||{},name=pet.pet_name||activeDevice?.name||'پت',can=activeDevice?.access!=='viewer',done=new Set(d.done_task_ids||[]),total=+d.total||0,completed=+d.completed||0,pct=total?Math.round(completed*100/total):0;const meta=[];if(profile.breed)meta.push(profile.breed);if(profile.weight_kg)meta.push(profile.weight_kg+' کیلو');if(profile.sex==='male')meta.push('نر');if(profile.sex==='female')meta.push('ماده');
 const tasks=(d.tasks||[]).map(t=>{const k=kind(t.kind),ok=done.has(t.id);return `<div class="cc-task ${ok?'done':''}"><button class="cc-check" ${!can||ok?'disabled':''} onclick="ccDone('${E(t.id)}')">${ok?'✓':k[0]}</button><div><b>${E(t.title)}</b><small>${t.time_of_day?E(t.time_of_day)+' · ':''}${E(k[1])}</small></div>${can?`<button class="cc-x" onclick="ccDelete('${E(t.id)}')">×</button>`:''}</div>`}).join('')||'<div class="cc-empty">برنامه‌ای برای امروز نداری.</div>';
 const logs=(d.logs||[]).slice(0,10).map(x=>{const k=kind(x.kind),t=new Date(x.happened_at),time=isNaN(t)?'':t.toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'});return `<div class="cc-log"><b>${k[0]}</b><div><strong>${E(x.title)}</strong><small>${E(time)}${x.note?' · '+E(x.note):''}</small></div></div>`}).join('')||'<div class="cc-empty">هنوز چیزی ثبت نشده.</div>';
 root.innerHTML=`<div class="cc-box cc-profile"><div><h3>${E(name)}</h3><div class="cc-muted">${total?`${completed} از ${total} کار امروز انجام شده`:'مراقبت روزانه را همین‌جا ساده نگه دار'}</div>${meta.length?`<div class="cc-meta">${meta.map(x=>`<span>${E(x)}</span>`).join('')}</div>`:''}${can?'<button class="btn small" style="margin-top:8px" onclick="ccProfile()">ویرایش پروفایل</button>':''}</div><div class="cc-score"><b>${total?pct+'٪':'—'}</b><span class="cc-muted">امروز</span></div></div>
 <div class="cc-box"><div class="cc-head"><div><b>برنامه امروز</b><div class="cc-muted">غذا، دارو، پیاده‌روی و کارهای تکراری</div></div>${can?'<button class="btn small primary" onclick="ccAdd()">＋ برنامه</button>':''}</div><div class="cc-tasks">${tasks}</div></div>
 ${can?`<div class="cc-box"><div class="cc-head"><b>ثبت سریع</b><span class="cc-muted">یک لمس</span></div><div class="cc-quick">${[['feed','🍽️','غذا'],['water','💧','آب'],['walk','🐾','پیاده‌روی'],['medication','💊','دارو'],['play','●','بازی']].map(x=>`<button onclick="ccQuick('${x[0]}','${x[2]}')"><b>${x[1]}</b>${x[2]}</button>`).join('')}</div></div>`:''}
 <div class="cc-box"><div class="cc-head"><b>امروز</b><span class="cc-muted">آخرین فعالیت‌ها</span></div>${logs}</div>`
}
async function loadCare(force=false){if(!activeId)return;try{render(await today(activeId,force))}catch(e){const b=document.querySelector('[data-tab="care"]');if(e.status===404){b?.remove();document.getElementById('careTab')?.remove()}else{const r=document.getElementById('ccCare');if(r)r.innerHTML='<div class="cc-empty">'+E(e.message)+'</div>'}}}
function decorate(){document.querySelectorAll('#cams .card').forEach((card,i)=>{const d=devices?.[i];if(!d)return;const a=card.querySelector('.actions');if(a&&!a.querySelector('[data-care]')){const b=document.createElement('button');b.className='btn small';b.dataset.care='1';b.textContent='مراقبت';b.onclick=()=>openCare(d.id);a.appendChild(b)}const body=card.querySelector('.body');if(!body||body.querySelector('.cc-mini'))return;const m=document.createElement('div');m.className='cc-mini';m.innerHTML='<span>مراقبت امروز</span><b>…</b>';body.insertBefore(m,a);today(d.id).then(x=>{if(m.isConnected)m.innerHTML=`<span>مراقبت امروز</span><b>${+x.completed||0}/${+x.total||0}</b>`}).catch(()=>m.remove())})}
async function applyCaps(id=activeId){if(!id)return;const c=await capabilities(id,true);if(activeId!==id)return;const hide=(el,no)=>{if(el)el.style.display=no?'none':''};hide(document.getElementById('torch'),c.torch_supported===false);hide(document.querySelector('#liveTab .zoom'),c.zoom_supported===false);hide(document.querySelector('#liveTab button[onclick*="rotateCamera"]'),c.camera_switch_supported===false);hide(document.querySelector('#liveTab .phrases'),c.speech_supported===false);hide(document.getElementById('talk'),c.talk_supported===false)}
window.openCare=async id=>{await openLive(id);showTab('care')};
window.ccDone=async id=>{try{await api(`/api/pet/devices/${activeId}/care/tasks/${encodeURIComponent(id)}/done`,{method:'POST',body:JSON.stringify({local_date:dateKey(),note:''})});cache.delete(activeId+':'+dateKey());await loadCare(true);toast('انجام شد')}catch(e){toast(e.message)}};
window.ccDelete=async id=>{if(!confirm('این برنامه حذف شود؟'))return;try{await api(`/api/pet/devices/${activeId}/care/tasks/${encodeURIComponent(id)}`,{method:'DELETE'});cache.delete(activeId+':'+dateKey());await loadCare(true);toast('حذف شد')}catch(e){toast(e.message)}};
window.ccQuick=async(k,title)=>{try{await api(`/api/pet/devices/${activeId}/care/logs`,{method:'POST',body:JSON.stringify({local_date:dateKey(),kind:k,title,note:''})});cache.delete(activeId+':'+dateKey());await loadCare(true);toast('ثبت شد')}catch(e){toast(e.message)}};
window.ccAdd=()=>openModal(`<button class="close" onclick="closeModal()">×</button><h3>برنامه روزانه</h3><form onsubmit="ccSaveTask(event)"><div class="field"><label>عنوان</label><input id="ccTitle" required maxlength="100" placeholder="مثلاً غذای عصر"></div><div class="cc-grid"><div class="field"><label>نوع</label><select id="ccKind"><option value="feed">غذا</option><option value="water">آب</option><option value="walk">پیاده‌روی</option><option value="medication">دارو</option><option value="grooming">نظافت</option><option value="play">بازی</option><option value="custom">سایر</option></select></div><div class="field"><label>ساعت</label><input id="ccTime" type="time"></div></div><button class="btn primary" style="width:100%">ذخیره</button></form>`);
window.ccSaveTask=async e=>{e.preventDefault();try{await api(`/api/pet/devices/${activeId}/care/tasks`,{method:'POST',body:JSON.stringify({title:document.getElementById('ccTitle').value.trim(),kind:document.getElementById('ccKind').value,time_of_day:document.getElementById('ccTime').value||null,days:[0,1,2,3,4,5,6],enabled:true})});closeModal();cache.delete(activeId+':'+dateKey());await loadCare(true);decorate();toast('برنامه اضافه شد')}catch(x){toast(x.message)}};
window.ccProfile=async()=>{try{const [p,s]=await Promise.all([api(`/api/pet/devices/${activeId}/profile`),api(`/api/pet/devices/${activeId}/settings`)]);openModal(`<button class="close" onclick="closeModal()">×</button><h3>پروفایل پت</h3><form onsubmit="ccSaveProfile(event)"><div class="cc-grid"><div class="field"><label>اسم</label><input id="ccName" maxlength="80" value="${E(s.pet_name||'')}"></div><div class="field"><label>نوع</label><select id="ccType"><option value="dog" ${s.pet_type==='dog'?'selected':''}>سگ</option><option value="cat" ${s.pet_type==='cat'?'selected':''}>گربه</option><option value="other" ${s.pet_type==='other'?'selected':''}>سایر</option></select></div><div class="field"><label>نژاد</label><input id="ccBreed" maxlength="80" value="${E(p.breed||'')}"></div><div class="field"><label>تاریخ تولد</label><input id="ccBirth" type="date" value="${E(p.birth_date||'')}"></div><div class="field"><label>جنسیت</label><select id="ccSex"><option value="unknown">نامشخص</option><option value="male" ${p.sex==='male'?'selected':''}>نر</option><option value="female" ${p.sex==='female'?'selected':''}>ماده</option></select></div><div class="field"><label>وزن (کیلو)</label><input id="ccWeight" type="number" min="0.1" max="250" step="0.1" value="${p.weight_kg??''}"></div><div class="field"><label>میکروچیپ</label><input id="ccChip" maxlength="80" value="${E(p.microchip||'')}"></div><div class="field"><label>دامپزشک</label><input id="ccVet" maxlength="120" value="${E(p.vet_name||'')}"></div><div class="field"><label>تلفن دامپزشک</label><input id="ccVetPhone" maxlength="50" value="${E(p.vet_phone||'')}"></div></div><div class="field"><label>یادداشت</label><textarea id="ccNotes" class="cc-text" maxlength="2000">${E(p.notes||'')}</textarea></div><button class="btn primary" style="width:100%">ذخیره</button></form>`)}catch(e){toast(e.message)}};
window.ccSaveProfile=async e=>{e.preventDefault();try{const old=await api(`/api/pet/devices/${activeId}/settings`),w=document.getElementById('ccWeight').value;await Promise.all([api(`/api/pet/devices/${activeId}/settings`,{method:'PUT',body:JSON.stringify({...old,pet_name:document.getElementById('ccName').value.trim(),pet_type:document.getElementById('ccType').value})}),api(`/api/pet/devices/${activeId}/profile`,{method:'PUT',body:JSON.stringify({breed:document.getElementById('ccBreed').value.trim(),birth_date:document.getElementById('ccBirth').value||null,sex:document.getElementById('ccSex').value,weight_kg:w?+w:null,microchip:document.getElementById('ccChip').value.trim(),vet_name:document.getElementById('ccVet').value.trim(),vet_phone:document.getElementById('ccVetPhone').value.trim(),notes:document.getElementById('ccNotes').value.trim()})})]);closeModal();cache.delete(activeId+':'+dateKey());await loadDevices();await loadCare(true);toast('پروفایل ذخیره شد')}catch(x){toast(x.message)}};
function hooks(){installTab();const oldTab=showTab;showTab=function(t){if(t==='care'){if(!activeId)return;['live','events','archive','settings'].forEach(x=>document.getElementById(x+'Tab')?.classList.add('hidden'));document.getElementById('careTab')?.classList.remove('hidden');document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab==='care'));loadCare();return}document.getElementById('careTab')?.classList.add('hidden');return oldTab(t)};const oldRender=renderDevices;renderDevices=function(){const r=oldRender();setTimeout(decorate,0);return r};const oldLive=openLive;openLive=async function(id){const r=await oldLive(id);setTimeout(()=>applyCaps(id),80);return r};const oldSettings=renderSettings;renderSettings=async function(){const r=await oldSettings();try{const c=await capabilities(activeId);if(c.sound_detection_supported===false)document.getElementById('sound')?.closest('.switchrow')?.classList.add('hidden')}catch{}return r};const h=document.querySelector('.head h1'),sub=document.querySelector('.head .muted');if(h)h.textContent='پت‌های من';if(sub)sub.textContent='دوربین، مراقبت و برنامه روزانه';setTimeout(decorate,0)}
installStyle();try{hooks()}catch(e){console.warn('CamCam pet care',e)}window.__camcamPetCareV1=true;
})();
